### ISSUE TITLE
How to use external application-{profile}.properties?

### ISSUE THREAD

**Issue by sgrillon14** [snicoll-scratches/spring-boot-daemon#15]
I add
`<startargument>-Dspring.profiles.active=dev</startargument>`

If my application-dev.properties is in "src/main/resources" is OK but I want use an external file.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by sgrillon14** [comment]
I find how to do and I create new [PR](https://github.com/snicoll-scratches/spring-boot-daemon/pull/16) with a sample
