### ISSUE TITLE
Improve Documentation Request

### ISSUE THREAD

**Issue by jdgiotta** [snicoll-scratches/spring-boot-daemon#3]
docs.spring.io references this project as a Windows Service example, but there isn't a lot of explaination in either docs.spring.io or your README

I'm looking for a breakdown of how this project and it's modules work together in order to fully grokk how such an implementation can be leveraged. The project on it's own works, but not so simple when trying to integrate into an existing project (i.e.; CommandLineRunner)

**Comment by snicoll** [comment]
For some reason, I was't receiving any notification on this repo. Sorry for the late reply. Yes, the doc can be improved. The project doesn't do anything funky besides calling Spring Boot with a certain flag so that it can invoke a clean shutdown from another process (i.e. the stop command).

That being said I don't see the link with `CommandLineRunner` (there isn't anything special about it, really).

**Comment by snicoll** [comment]
Closing due to the lack of feedback.
